#!/usr/bin/env python

# This file is part of IETView
# Copyright (C) 2008,2009,2010 Jeffrey Panczyk <jpanczyk@gmail.com>
#
# IETView is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# IETView is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with IETView.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys

dir = os.path.dirname(os.path.abspath(sys.argv[0]))

if os.path.exists(dir + '/' + 'src/IETView.py'):
    from src import IETView
    print 'Running from current directory for testing.'
else:
    from IETView import IETView

iet_view = IETView.IetView()
iet_view.run()

